allow-branch = ["main"]

push = true
push-tags = true

tag = true
tag-name = "v{{version}}"
tag-message = "Version {{version}}"

commit = true
commit-message = "Release: Version {{version}}"

publish = true
